targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_format: single_file
          locale_handling: true
          flutter_integration: false
          namespaces: false
          translate_var: local
          enum_name: AppLocale
          translation_class_visibility: public
          key_case: camel
          key_map_case: camel
          param_case: camel
