version: '3.9'
services:
  radio_horizon:
    image: ghcr.io/tomassasovsky/radio-horizon.dart:latest
    container_name: radio_horizon
    expose:
      - 8080
    env_file:
     - .env/.env.production
    links:
      - lavalink
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink
    restart: always
    expose:
      - 2333
    volumes:
     - ./lavalink.yml:/opt/Lavalink/application.yml
