services:
  radio_horizon:
    image: ghcr.io/tomassasovsky/radio-horizon.dart:latest
    container_name: radio_horizon
    expose:
      - 8080
    env_file:
     - .env/.env.production
    links:
      - lavalink
      - shazam_api
    depends_on:
      - lavalink
      - shazam_api

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: lavalink
    restart: always
    expose:
      - 2333
    volumes:
     - ./lavalink.yml:/opt/Lavalink/application.yml

  shazam_api:
    build:
      context: ./shazam_api
    expose:
      - 5000
    volumes:
      - ./shazam_api:/app
    environment:
      FLASK_ENV: production
