services:
  radio_horizon:
    image: ghcr.io/tomassasovsky/radio-horizon.dart:latest
    container_name: radio_horizon
    restart: unless-stopped
    expose:
      - 8080
    env_file:
     - .env/.env.development
    links:
      - lavalink
      - shazam_api
    depends_on:
      - lavalink
      - shazam_api

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    expose:
      - 2333
    volumes:
     - ./output.lavalink.yml:/opt/Lavalink/application.yml
    depends_on:
      update_lavalink_config:
        condition: service_completed_successfully

  shazam_api:
    image: ghcr.io/tomassasovsky/shazam_api:latest
    container_name: shazam_api
    restart: unless-stopped
    expose:
      - 5000
    environment:
      FLASK_ENV: production

  update_lavalink_config:
    image: ghcr.io/tomassasovsky/update-lavalink-config:latest
    container_name: update_lavalink_config
    restart: no
    volumes:
      - ./lavalink.yml:/app/lavalink.yml
      - ./:/output-dir
    env_file:
      - .env/.env.development
    command: ["--input", "lavalink.yml", "--output", "/output-dir/output.lavalink.yml"]
