global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rg'
    scrape_interval: 5s
    static_configs:
      - targets: ['radio_horizon:8080']