name: custom_lavalink
description: A tool that automatically edits the lavalink.yml file to populate the secrets from environment variables.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  dotenv: ^4.2.0
  logging: ^1.3.0
  yaml_edit: ^2.2.1
