name: radio_horizon

on:
  pull_request:
    paths:
      - ".github/workflows/radio_horizon.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/radio_horizon.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: ./.github/workflows/dart_package.yaml
    with:
      min_coverage: 0
      analyze_directories: lib

  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: |
          dart pub get
